services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: storefront
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: User1name2
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=storefront.settings
      - DB_NAME=storefront
      - DB_USER=postgres
      - DB_PASSWORD=User1name2
      - DB_HOST=db